<?php
    $lang['number']   = 'Reference';
    $lang['date']     = 'Date';
    $lang['time']     = 'Time';
    $lang['due']      = 'Due date';
    $lang['to']       = 'Billing to';
    $lang['from']     = 'Billing from';
    $lang['product']  = 'Product';
    $lang['qty']      = 'Qty';
    $lang['price']    = 'Price';
    $lang['discount'] = 'Discount';
    $lang['vat']      = 'Vat';
    $lang['total']    = 'Total';
    $lang['page']     = 'Page';
    $lang['page_of']  = 'of';
